export const GAME_CONSTANTS = {
    FINISH_LINE_DISTANCE: 1000,
    FEEDBACK_DELAY_MS: 1500,
    FRICTION_SPIKE_DURATION_MS: 2000,
    FRICTION_COEFFICIENT: 0.8,
    DISCONNECTION_GRACE_PERIOD_MS: 10000,
    RESONANCE_STREAK_THRESHOLD: 5
};
